log_level: debug
http:
  port: 9099
  host: localhost
  ping_timeout: 2s
postgres:
  db_con_format: postgres
  db_host: postgres
  db_port: 5432
  db_user: user
  db_pass: password
  db_name: InHouseAd_assignment
  db_tbl_user: test-user
  db_tbl_category: test-categories
  db_tbl_product: test-product
  db_tbl_product_category: test-product_category
data_collect_time: 1h
data_collect_link: https://emojihub.yurace.pro/api/all
refresh_ttl: 1h
token_ttl: 240h
secret_key: test-key